### PR TITLE
feat: windows support

### PR DESCRIPTION
**Pull request by 1k-off**
Added functionality to run on windows.

It will work on newer versions on windows with openssl installed separately. Otherwise encryption settings will be ignored. 

Currently unavailable:
- splitter. Can be available by using thirdparty tools (such as 7zip), some powershell commands or internal go functionality. But as system command executions used everywhere, and powershell scripts looks not so good in this case - I did not changed this. 
- running as a daemon. Instead of this, added an instructions to run as a windows service using nssm.

Also added handling for `ctrl + c`.

Let me know if you are satisfied with this implementation so that I can add pipeline changes, or make the necessary changes to code.

### CODE REVIEW

**Comment by huacnlee** [comment]
Sorry, I am not plan to support Windows.

This tool has too many Linux tools dependency, your changes just let GoBackup can run on Windows, but the core features of GoBackup is uses a lot of third part tool (mysqldump, pg_dump ...) to perform backup.

When we merge this, we will need to resolve a lot of issues on Windows user.

**Comment by huacnlee** [comment]
Ref #60

**Comment by 1k-off** [comment]
Is there a chance to convince you? Now windows takes more and more from linux. It [now has tar](https://learn.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows) for example. Database clients, among with the additional software needs to be installed in both windows or linux.

I'll be honest with you: I hate windows :) Bit I also honest with myself: there are quite a lot of Windows servers in the world, unfortunately in my infrastructure too. And sometimes there is a need for a simple and effective backup solution. 

And it's hard to maintain fork only for this purposes :)

Sorry for being intrusive, as I said, I'm just trying to understand is there any chance to see windows support in the original repo, or should I make and maintain own fork. Because I still want to have updates and need some solution that will work in both systems.

**Comment by JamCh01** [comment]
@1k-off Can you provide a release version? I am not a Go developer and I don't know how to configure the development environment. :D

**Comment by 1k-off** [comment]
> @1k-off Can you provide a release version? I am not a Go developer and I don't know how to configure the development environment. :D

Hi! Sorry, but most probably can not.  At least not now.
I investigated code a bit deeper and see that there are so many things that relies on linux binaries. That things must be rewrited and  properly tested on windows. 

I added a base fixes like paths and messages for unsupported functionality (for example, splitter functionality will not work on windows at all without thirdparty tools). But I haven't tested it yet. Perhaps I was a little hasty in offering this functionality.

And right now I have no time for development. I need windows version for work too, so I hope, will return to this later.

**Comment by JamCh01** [comment]
> > @1k-off Can you provide a release version? I am not a Go developer and I don't know how to configure the development environment. :D
> 
> Hi! Sorry, but most probably can not. At least not now. I investigated code a bit deeper and see that there are so many things that relies on linux binaries. That things must be rewrited and properly tested on windows.
> 
> I added a base fixes like paths and messages for unsupported functionality (for example, splitter functionality will not work on windows at all without thirdparty tools). But I haven't tested it yet. Perhaps I was a little hasty in offering this functionality.
> 
> And right now I have no time for development. I need windows version for work too, so I hope, will return to this later.

wow~thanks for your reply~waiting for your good news

**Pull request closed without merging**
